name: Clojure CI

on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    container: clojure:temurin-17-lein-2.10.0

    steps:
      # 1. Получаем код
      - uses: actions/checkout@v3

      # 2. Запускаем форматирование (cljfmt)
      - name: Format code
        run: clojure -M:fmt

      # 3. Запускаем линт (clj-kondo)
      - name: Lint code
        run: clojure -M:lint

      # 4. Прогоняем тесты
      - name: Run tests
        run: clojure -M:test
