name: Clojure CI

on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем код
      - uses: actions/checkout@v3

      # 2. Устанавливаем Clojure через официальный Action
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12
        with:
          cli: 1.11.3.1165
          tools-deps: true

      # 3. Запускаем форматирование (cljfmt)
      - name: Format code
        run: clojure -M:fmt

      # 4. Запускаем линт (clj-kondo)
      - name: Lint code
        run: clojure -M:lint

      # 5. Прогоняем тесты
      - name: Run tests
        run: clojure -M:test
