name: Clojure CI

on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    container: clojure:temurin-17-lein-2.10.0

    steps:
      # 1. Получаем код
      - uses: actions/checkout@v3

      # 2. Устанавливаем необходимые утилиты
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y unzip curl

      # 3. Устанавливаем Java
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      # 4. Устанавливаем Clojure CLI
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.2.1565
          clj-kondo: 2025.07.28

      # 5. Запускаем форматирование (cljfmt)
      - name: Format code
        run: clojure -M:fmt

      # 6. Запускаем линт (clj-kondo)
      - name: Lint code
        run: clojure -M:lint

      # 7. Прогоняем тесты
      - name: Run tests
        run: clojure -M:test
